# DISTRIBUTION DIMENSIONALITY

## Load libraries

In [1]:
from functools import partial

import pymc as pm
import numpy as np
import pytensor.tensor as pt

WARNING (pytensor.tensor.blas): Using NumPy C-API based implementation for BLAS functions.


## Univariate distribution example

In [2]:
normal_dist = pm.Normal.dist()

In [3]:
# Just patching the draw function for reproducibility
rng = np.random.default_rng(seed = sum(map(ord, 'dimensionality')))

In [6]:
draw = partial(pm.draw, random_seed = rng)

In [9]:
normal_draw = draw(normal_dist)

normal_draw, normal_draw.ndim

(array(0.98810294), 0)

In [10]:
normal_dist.owner.op.ndim_supp

0

## Explicit batch dimensions

In [13]:
normal_dists = pm.math.stack([pm.Normal.dist() for _ in range(3)])
draw(normal_dists)

array([ 0.81833093, -1.20771815, -1.57321429])

In [15]:
normal_dists = pm.Normal.dist(shape = (3, ))
draw(normal_dists)

array([-1.00245596,  0.98739732,  0.42147186])

In [16]:
normal_dists = pm.Normal.dist(shape=(4, 3))
draw(normal_dists)

array([[ 0.06413633,  0.29893485, -2.48072495],
       [ 0.40366984,  1.39930982, -1.45070547],
       [-1.59553347,  0.6762147 , -0.08635607],
       [-0.59883178, -2.88933325,  0.13339571]])